# Generated by Django 2.1.2 on 2019-02-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ride_count',
            field=models.IntegerField(default=0),
        ),
    ]
