# Generated by Django 2.1.2 on 2019-01-18 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('dealer_name', models.CharField(max_length=100)),
                ('dealer_address', models.CharField(max_length=300)),
                ('dealer_lat', models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=9)),
                ('dealer_lon', models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=9)),
                ('status', models.BooleanField(default=False, null=True, verbose_name='on/off status')),
                ('email', models.EmailField(default=0, max_length=254)),
                ('password', models.CharField(default=0, max_length=50)),
                ('opentime', models.TimeField(default='20:00')),
                ('closetime', models.TimeField(default='20:00')),
                ('last_login', models.CharField(default=0, max_length=60)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dealers',
                'ordering': ('-d_id',),
                'db_table': 'dealer_info',
            },
        ),
    ]
