# Generated by Django 2.1.2 on 2018-11-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('dealer_name', models.CharField(max_length=100)),
                ('dealer_address', models.CharField(max_length=300)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('opentime', models.DateTimeField()),
                ('closetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'dealer_information',
                'verbose_name_plural': 'Dealers',
                'ordering': ('-d_id',),
            },
        ),
    ]
