# Generated by Django 2.1.2 on 2018-11-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='lat',
            new_name='dealer_lat',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='lon',
            new_name='dealer_lon',
        ),
        migrations.AlterModelTable(
            name='dealer',
            table='dealer_info',
        ),
    ]
