# Generated by Django 2.1.2 on 2018-11-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_auto_20181104_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='closetime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='opentime',
            field=models.TimeField(),
        ),
    ]
