# Generated by Django 2.1.2 on 2018-10-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0002_auto_20181023_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='uid',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
