# Generated by Django 2.1.2 on 2018-10-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0003_auto_20181023_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='PhoneModel',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='mobile',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
