# Generated by Django 2.1.2 on 2018-10-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0004_auto_20181024_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_login',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AlterModelTable(
            name='userprofileinfo',
            table='uaccounts_userprofileinfo',
        ),
    ]
