# Generated by Django 2.1.2 on 2019-01-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, db_column='image', null=True, upload_to='bike/category/')),
                ('discount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
