# Generated by Django 2.1.2 on 2019-01-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderInfo',
            fields=[
                ('uid', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('mid', models.IntegerField(default=0)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('start_date', models.CharField(choices=[(1, '18 Jan'), (2, '19 Jan'), (3, '20 Jan'), (4, '21 Jan')], max_length=6)),
                ('start_time', models.CharField(max_length=8)),
                ('end_date', models.CharField(choices=[(1, '18 Jan'), (2, '19 Jan'), (3, '20 Jan'), (4, '21 Jan')], max_length=6)),
                ('end_time', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
