# Generated by Django 2.1.2 on 2019-01-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderInfo',
            fields=[
                ('order_id', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('u_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(default=0, max_length=40)),
                ('d_id', models.IntegerField(default=0)),
                ('m_id', models.IntegerField(default=0)),
                ('booked_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(max_length=6)),
                ('start_time', models.CharField(max_length=8)),
                ('end_date', models.DateField(max_length=6)),
                ('end_time', models.CharField(max_length=8)),
                ('duration', models.CharField(default=0, max_length=30)),
                ('price_hour', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('price_day', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dealer_money', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
