# Generated by Django 2.1.2 on 2018-12-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorderinfo',
            name='mid',
            field=models.IntegerField(default=0),
        ),
    ]
