# Generated by Django 2.1.2 on 2019-01-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorderinfo',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
