# Generated by Django 2.0.2 on 2019-03-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190313_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorderinfo',
            name='u_id',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
