# Generated by Django 2.0.2 on 2019-03-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190313_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorderinfo',
            name='order_id',
            field=models.BigIntegerField(),
        ),
    ]
