# Generated by Django 2.1.2 on 2019-01-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
                'ordering': ('-created',),
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('specification', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('c_id', models.ForeignKey(db_column='c_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Category')),
                ('d_id', models.ForeignKey(db_column='d_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.Dealer')),
            ],
            options={
                'verbose_name_plural': 'Models/Variants',
                'ordering': ('-created',),
                'db_table': 'category_model',
            },
        ),
        migrations.CreateModel(
            name='CategoryModelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='bike/models/')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='bike/models/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='bike/models/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='bike/models/')),
            ],
            options={
                'verbose_name_plural': 'Model Images',
                'db_table': 'category_model_image',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='bike/category/')),
            ],
            options={
                'verbose_name_plural': 'Category Images',
                'db_table': 'category_image',
            },
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='model_image',
            field=models.ForeignKey(db_column='image', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.CategoryModelImage'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(db_column='image', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Image'),
        ),
    ]
