# Generated by Django 2.1.2 on 2018-11-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_auto_20181104_0847'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='d_id',
            field=models.ForeignKey(db_column='d_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.Dealer'),
        ),
    ]
