# Generated by Django 2.1.2 on 2018-12-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_categorymodel_d_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='bike/category/'),
        ),
        migrations.AddField(
            model_name='image',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='bike/category/'),
        ),
        migrations.AddField(
            model_name='image',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='bike/category/'),
        ),
    ]
