# Generated by Django 2.1.2 on 2019-02-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190129_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='is_delivery',
            field=models.BooleanField(default=False, verbose_name='Delivery'),
        ),
    ]
