# Generated by Django 2.0.2 on 2019-03-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_categorymodel_is_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
