# Generated by Django 2.1.2 on 2018-12-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20181219_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img3',
        ),
        migrations.AddField(
            model_name='categorymodelimage',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='bike/category/'),
        ),
        migrations.AddField(
            model_name='categorymodelimage',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='bike/category/'),
        ),
        migrations.AddField(
            model_name='categorymodelimage',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='bike/category/'),
        ),
    ]
