# Generated by Django 2.1.2 on 2018-12-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20181219_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodelimage',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='bike/models/'),
        ),
        migrations.AlterField(
            model_name='categorymodelimage',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='bike/models/'),
        ),
        migrations.AlterField(
            model_name='categorymodelimage',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='bike/models/'),
        ),
    ]
