# Generated by Django 2.1.2 on 2018-10-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20181031_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
