# Generated by Django 2.1.2 on 2018-12-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20181219_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
